### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [pmarkowsky/dash#8]
wow, this is a fantastic tool! linked to your project from our website now: http://www.capstone-engine.org/showcase.html & http://www.keystone-engine.org/showcase/

keep it up, cheers!

**Comment by pmarkowsky** [comment]
Thanks, this is still very much a work in progress, based on a much older
tool that was using nasm as the assembler, and distorm3.

**Comment by aquynh** [comment]
just an opinion: you named this "Dash", but the project name is "Webasm", which is a bit confused. 
how about changing the project name to "dash"?

**Comment by pmarkowsky** [comment]
Good point. Done.

**Comment by aquynh** [comment]
great, then all the references to "webasm" in README should be changed to "dash", too?

**Comment by pmarkowsky** [comment]
Changed. Closing this issue. Thanks again for the shout out.
